site_name: FEniCSUI documentaitons


nav:
    - Home: index.md
    - Tutorial: tutorial.md
    - Solvers Reference: solvers.md
    - Back-end API Reference: backendAPI.md
    - Front-end API Reference: frontEndAPI.md
    - developers: development.md
    - About: about.md

theme: readthedocs