# Generated by Django 3.0.6 on 2020-05-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysesHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solverresults',
            old_name='result',
            new_name='path',
        ),
    ]
