# Generated by Django 3.0.6 on 2020-05-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visualizationMesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh', models.TextField()),
                ('faces', models.TextField()),
                ('edges', models.TextField()),
                ('points', models.TextField()),
                ('boundingBox', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projects')),
            ],
        ),
    ]
