# Generated by Django 3.0.6 on 2020-05-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeshGenerator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visualizationMesh',
        ),
    ]
